### ISSUE TITLE
Hot Reload seems not to work properly for ASP.NET Core

### ISSUE THREAD

**Issue by xhafan** [xhafan/coreddd#26]
Error:
```
2022-04-26 13:06:35.722 +02:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'SmartGuide.Core.Domain.PointOfInterest' to type 'NHibernate.Proxy.INHibernateProxy'.
   at PointOfInterestProxy.NHibernate.Proxy.INHibernateProxy.get_HibernateLazyInitializer()
   at NHibernate.Engine.StatefulPersistenceContext.Clear()
   at NHibernate.Impl.SessionImpl.Close()
   at NHibernate.Impl.SessionImpl.Dispose(Boolean isDisposing)
   at NHibernate.Impl.SessionImpl.Dispose()
   at CoreDdd.Nhibernate.UnitOfWorks.NhibernateUnitOfWork.RollbackAsync()
   at CoreDdd.AspNetCore.Middlewares.BaseUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next, IUnitOfWork unitOfWork)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
How to replicate: Hot Reload a change, execute the change couple of times.

**Comment by xhafan** [comment]
todo: create a test case to verify the issue: https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md#creating-a-test-case-to-verify-the-issue

**Comment by shmatt** [comment]
Came across this issue when searching for a solution to the same problem I am facing, but not using coreddd.

It seems that this is an issue with nhibernate itself, and not specifically with this library
